### ISSUE TITLE
Bugbear Speed

### ISSUE THREAD

**Issue by PaperMonkeyLord** [TNychka/Pathfinder2eConversion#73]
Noticed bugbear base speed is 20. Is this correct? Seems oddly low. If intentional could someone walk me through the thought process? They've never been slower than humans in any previous iteration.

**Comment by TNychka** [comment]
Hey! 
The decision for a 20ft base speed is intentional. I wanted them to be slow and lumbering - the 20ft base speed is also seen in Dwarves which are the type of slow but tough trope I wanted to go for. However like you mentioned, the monster bugbears have a base 25ft movement speed.
Cross-referencing with Orcs it looks like 25ft and 10hp is balanced, so I'm going to bump bugbears up to 25ft.
Thanks for the input :D

**Comment by TNychka** [comment]
Closed in 3ae32c9fe431e0265addc7ecb6be1e0d92c9d029
